---
title: "Clase-8-Temas"
author: "Gonzalo Ramirez"
date: "2023-05-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(extrafont)
```


```{r}
incidencia         <- c("Brocal roto", "Tapa desnivelada", "Tapa faltante", "Tapa floja", "Tapa hundida", "Tapa rota")
reclamos_totales   <- c(223, 163, 833, 46, 1000, 330)
reclamos_poligonos <- c(20, 12, 72, 4, 71, 32)
```


```{r}
incidencias_totales <- data.frame(Incidencia = incidencia, Frecuencia = reclamos_totales)
incidencias_totales <- arrange(incidencias_totales, desc(Frecuencia))
incidencias_totales
```


```{r}
incidencias_poligonos <- data.frame(Incidencia = incidencia, Frecuencia = reclamos_poligonos)
incidencias_poligonos <- arrange(incidencias_poligonos, desc(Frecuencia))
incidencias_poligonos
```

```{r}
font_import()
```


```{r}
loadfonts(device = "win", quiet = TRUE)
```


```{r}
fonts()
```


```{r}
incidencias_totales %>% 
  ggplot(aes(x = factor(Incidencia, levels = Incidencia), Frecuencia, fill = Incidencia)) +
  geom_col() +
  theme_minimal() +
  geom_text(aes(label = Frecuencia), vjust = -0.5, color = "gray30", size = 3.5) +
  coord_cartesian(ylim = c(0,1200)) +
  scale_fill_manual(values = c("#5f9595", "#80ce87", "#f0bc68", "#8a8fef", "#ba74cc", "#af7351")) +
  labs(
    title    = "Cantidad de reclamos por incidencia",
    subtitle = "Informe AySA",
    caption  = "Total de casos: 2595"
  ) +
  theme(
    axis.title.x     = element_blank(),
    axis.title.y     = element_blank(),
    panel.grid.major = element_line(color = "gray90"),
    text             = element_text(family = "Open Sans Medium"),
    legend.position  = "none",
    plot.margin      = margin(30, 30, 30, 30),
    plot.subtitle    = element_text(color = "gray40", margin = margin(0, 0, 20, 0)),
    plot.caption     = element_text(color = "gray40", margin = margin(20, 0, 0, 0), face = "italic")
  )
```

```{r}
incidencias_poligonos %>% 
  ggplot(aes(x = factor(Incidencia, levels = Incidencia), Frecuencia, fill = Incidencia)) +
  geom_col() +
  theme_minimal() +
  geom_text(aes(label = Frecuencia), vjust = -0.5, color = "gray30", size = 3.5) +
  coord_cartesian(ylim = c(0,80)) +
  scale_fill_manual(values = c("#5f9595", "#80ce87", "#f0bc68", "#8a8fef", "#ba74cc", "#af7351")) +
  labs(
    title    = "Cantidad de reclamos por incidencia dentro de poligonos",
    subtitle = "Informe AySA",
    caption  = "Total de casos: 211"
  ) +
  theme(
    axis.title.x     = element_blank(),
    axis.title.y     = element_blank(),
    panel.grid.major = element_line(color = "gray90"),
    text             = element_text(family = "Open Sans Medium"),
    legend.position  = "none",
    plot.margin      = margin(30, 30, 30, 30),
    plot.subtitle    = element_text(color = "gray40", margin = margin(0, 0, 20, 0)),
    plot.caption     = element_text(color = "gray40", margin = margin(20, 0, 0, 0), face = "italic")
  )
```


























